"""add likes to posts

Revision ID: 9a7f80e26d7f
Revises: e7ee388272d4
Create Date: 2026-05-06 23:07:57.490316

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a7f80e26d7f"
down_revision: Union[str, Sequence[str], None] = "e7ee388272d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("likes", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "likes")
    # ### end Alembic commands ###
